site_name: uvi-example
repo_url: https://github.com/shaneholloman/uvi-example
site_url: https://shaneholloman.github.io/uvi-example
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Shane Holloman
edit_uri: edit/main/docs/
repo_name: shaneholloman/uvi-example
copyright: Maintained by <a href="https://shaneholloman.com">Shane Holloman</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [uvi_example]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shaneholloman/uvi-example
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/uvi-example

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
